# Generated by Django 4.0.3 on 2022-03-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_code',
            new_name='code',
        ),
    ]
