# Generated by Django 4.0.3 on 2022-03-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_rename_project_code_project_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.project')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
